-- DATE AND TIME
CREATE DATABASE IF NOT EXISTS EMPLOYEE;
USE EMPLOYEE;
CREATE TABLE IF NOT EXISTS EMPLOYEE(
    ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    SALARY INT,
    DEPARTMENT VARCHAR(50)
);

INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT) VALUES
    (1, 'SHALU', 10000, 'HR'),
    (2, 'RIYA', 5000, 'MANAGER'),
    (3, 'NIRMALA', 7000, 'MANAGER'),
    (4, 'LAVU', 5000, 'MANAGER'),
    (5, 'MOHANAPRIYA', 50000, 'CEO'),
    (6, 'VANI', 20000, 'HR');

SELECT * FROM EMPLOYEE;
ALTER TABLE EMPLOYEE ADD COLUMN HIRE_DATE DATE;

UPDATE  employee
SET Hire_Date="2014-10-05"
WHERE DEPARTMENT = "MANAGER";
SELECT NOW(); 
SELECT DATE(NOW()); 
SELECT CURDATE();
SELECT DATE_FORMAT(CURDATE(),'%d/%m/%Y');
SELECT DATEDIFF(CURDATE(),'2020-01-01') DAYS;
