-- INDEX
CREATE DATABASE IF NOT EXISTS EMP;
USE EMP;
DROP DATABASE EMP;

CREATE TABLE IF NOT EXISTS EMP (
    ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    SALARY INT,
    DEPARTMENT VARCHAR(50)
);

INSERT INTO EMP (ID, NAME, SALARY, DEPARTMENT) VALUES
    (1, 'SHALU', 10000, 'HR'),
    (2, 'RIYA', 5000, 'MANAGER'),
    (3, 'NIRMALA', 7000, 'MANAGER'),
    (4, 'LAVU', 5000, 'MANAGER'),
    (5, 'MOHANAPRIYA', 50000, 'CEO'),
    (6, 'VANI', 20000, 'HR');
    SHOW INDEX FROM EMP;
    
CREATE INDEX name_index ON EMP(NAME); 
SELECT * FROM EMP;
ALTER TABLE EMP
DROP INDEX name_index;
SELECT * FROM EMP;
ALTER TABLE EMP
ADD INDEX(NAME); 
SELECT * FROM EMP;
    