-- ON DELETE
CREATE DATABASE IF NOT EXISTS EP;
USE EP;


CREATE TABLE IF NOT EXISTS EP (
    ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    SALARY INT,
    DEPARTMENT VARCHAR(50)
);

INSERT INTO EP(ID, NAME, SALARY, DEPARTMENT) VALUES
    (1, 'SHALU', 10000, 'HR'),
    (2, 'RIYA', 5000, 'MANAGER'),
    (3, 'NIRMALA', 7000, 'MANAGER'),
    (4, 'LAVU', 5000, 'MANAGER'),
    (5, 'MOHANAPRIYA', 50000, 'CEO'),
    (6, 'VANI', 20000, 'HR');

CREATE DATABASE EMP3;
USE EMP3;


CREATE TABLE IF NOT EXISTS EMP3 (
    ID INT,
    PHONE BIGINT,
    INDEX (ID), 
    CONSTRAINT FK_employeeID FOREIGN KEY (ID) REFERENCES EMPLOYEE.EMPLOYEE(ID) 
    ON DELETE cascade
    -- ON DELETE SET NULL
);
SELECT * FROM EMP3;
INSERT INTO EMP3 (ID, PHONE) VALUES 
    (1, 882971216),
    (2, 9840163331),
    (3, 888552475);
USE EMP;
SELECT * FROM EMP;
USE EP;
SELECT * FROM EP;

