-- UPDATE AND DELETE
CREATE TABLE EMPLOYEE(
    ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    SALARY INT,
    DEPARTMENT VARCHAR(50)
);

INSERT INTO EMPLOYEE(ID, NAME, SALARY, DEPARTMENT) VALUES
    (1, 'SHALU', 10000, 'HR'),
    (2, 'RIYA', 5000, 'MANAGER'),
    (3, 'NIRMALA', 7000, 'MANAGER'),
    (4, 'LAVU', 5000, 'MANAGER'),
    (5, 'MOHANAPRIYA', 50000, 'CEO'),
    (6, 'VANI', 20000, 'HR');
SELECT * FROM EMPLOYEE;
UPDATE EMPLOYEE
SET DEPARTMENT = 'ENGINEER'
WHERE DEPARTMENT = 'MANAGER';
SELECT * FROM EMPLOYEE;
DELETE FROM EMPLOYEE
WHERE ID=1;
SELECT * FROM EMPLOYEE;

