-- where clause
CREATE TABLE STU( 
    ID INT,
    NAME VARCHAR(30),
    GPA DECIMAL(3,2),
    PRIMARY KEY(ID),
    SALARY INT
);
-- Insert some data
INSERT INTO STU(ID,NAME,GPA,SALARY) VALUES(5,"Aashiq",7.6,1000);
INSERT INTO STU(ID,NAME,GPA,SALARY) VALUES(6,"Mohanapriya",6.6,2000);
INSERT INTO STU(ID,NAME,GPA,SALARY) VALUES(4,"Ammu",8.6,3000);
SELECT * FROM STU
WHERE SALARY >= 2000 AND NAME="Ammu";
SELECT * FROM STU
WHERE SALARY = 0 OR NAME="Aashiq";
SELECT * FROM STU
WHERE NAME IN ("Aashiq");
SELECT * FROM STU
WHERE NAME NOT IN ("Aashiq");
SELECT * FROM STU
WHERE SALARY BETWEEN 2000 AND 3000;
SELECT * FROM STU
WHERE SALARY BETWEEN 2000 AND 3000
LIMIT 1;

